package com.github.liuyiyou.spring.jdbc;

import junit.framework.Assert;
import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Created with IntelliJ IDEA.
 * User: liuyiyou
 * Date: 14-7-24
 * Time: 下午1:31
 * To change this template use File | Settings | File Templates.
 */
public class JdbcTemplateTest {

    private static JdbcTemplate jdbcTemplate;

    //在所有测试方法之前执行，且执行一次
    @BeforeClass
    public static void setUpClass(){
        String url = "jdbc:hsqldb:mem:test";
        String username = "sa";
        String password = "";
        DriverManagerDataSource dataSource = new DriverManagerDataSource(url,username,password);
        dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
        jdbcTemplate = new JdbcTemplate(dataSource);

    }

    @Test
    public void testQuery(){
        String sql = "select * from INFORMATION_SCHEMA.SYSTEM_TABLES";
        jdbcTemplate.query(sql,new RowCallbackHandler() {
            @Override
            public void processRow(ResultSet resultSet) throws SQLException {
                String value = resultSet.getString("TABLE_NAME");
                System.out.println("Column TABLENAE: "+ value);
            }
        });
    }


    //表示在测试方法之前和之后的方法，对于每个测试方法都执行一次
    @Before
    public void setUp(){
        String createTableSql = "create memory table test (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(100))";
        jdbcTemplate.update(createTableSql);
    }

    @After
    public void testDown(){
        String dropTableSql = "drop table test";
        jdbcTemplate.execute(dropTableSql);
    }


    @Test
    public void testCURD(){
        insert();
        delete();
        update();
        select();
    }

    public void insert(){
        String insertSql = "insert into test(name) values ('name1')";
        String insertSql2= "insert into test(name) values ('name2')";
        jdbcTemplate.update(insertSql);
        jdbcTemplate.update(insertSql2);
        String selectSql = "select count(*) from test";
        Assert.assertEquals(2,jdbcTemplate.queryForInt(selectSql));
    }

    public void delete(){
        String deleteSql = "delete from test where name = ?";
        jdbcTemplate.update(deleteSql,new Object[]{"name2"});
        String selectSql = "select count(*) from test";
        Assert.assertEquals(1,jdbcTemplate.queryForInt(selectSql));
    }

    public void update(){
        String updateSql = "update test set name = 'name3' where name = ? ";
        String selectSql = "select count(*) from test where name = 'name3'";
        jdbcTemplate.update(updateSql,new Object[]{"name1"});
        Assert.assertEquals(1,jdbcTemplate.queryForInt(selectSql));

    }

    public void select(){
        String selectSql = "select * from test ";
        jdbcTemplate.query(selectSql,new RowCallbackHandler() {
            @Override
            public void processRow(ResultSet resultSet) throws SQLException {
                System.out.println("id: "+resultSet.getInt("id"));
                System.out.println("name: "+resultSet.getString("name"));
            }
        });
    }






}
